name: Build And Deploy Maven Site to GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'multi-module-build/**'  # only trigger on changes in the multi-module-build directory
  pull_request:
    branches: [ main ]
    paths:
      - 'multi-module-build/**'
  workflow_dispatch: 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pages: write
      id-token: write
      actions: read  # adding actions permission to read actions metadata

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'  # Version of Java to use
        distribution: 'temurin'

    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/multi-module-build/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Build project
      run: |
        cd multi-module-build
        mvn clean compile

    - name: Run tests
      run: |
        cd multi-module-build
        mvn test

    - name: Generate Maven site
      run: |
        cd multi-module-build
        mvn site site:stage

    - name: Prepare site for subdirectory deployment
      run: |
        # Create a new directory structure for Pages deployment
        mkdir -p pages-deploy/site
        
        # Copy the Maven site to the site subdirectory
        cp -r multi-module-build/target/staging/* pages-deploy/site/
        
        # Copy the custom homepage from .github/homepage directory
        cp .github/homepage/index.html pages-deploy/

    - name: List prepared files (for debugging)
      run: |
        echo "Contents of pages-deploy directory:"
        ls -la pages-deploy/
        echo "Contents of pages-deploy/site directory:"
        ls -la pages-deploy/site/

    - name: Setup Pages
      uses: actions/configure-pages@v4
      with:
        enablement: true  # turn on GitHub Pages

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './pages-deploy'
        name: github-pages-${{ github.run_number }}

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
      with:
        artifact_name: github-pages-${{ github.run_number }}